package com.armakers3d.testsupport;

import com.armakers3d.shared.notification.EmailSender;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

/**
 * Test double replacing {@code SmtpEmailSender} under the {@code test} profile. Captures every
 * "sent" message so security/contract tests can recover the plaintext OTP code that was actually
 * issued (impossible to do any other way, since the persisted value is a one-way hash — FR-014)
 * without ever needing a real mailbox or SMTP server.
 */
@Component
@Profile("test")
public class CapturingEmailSender implements EmailSender {

    /** A 6-digit code as generated by {@code OtpService} (research.md #1). */
    private static final Pattern CODE_PATTERN = Pattern.compile("\\b(\\d{6})\\b");

    public record SentEmail(String to, String subject, String body) {}

    private final List<SentEmail> sent = new ArrayList<>();

    @Override
    public void send(String toEmail, String subject, String body) {
        sent.add(new SentEmail(toEmail, subject, body));
    }

    public List<SentEmail> getSent() {
        return sent;
    }

    public SentEmail lastFor(String email) {
        for (int i = sent.size() - 1; i >= 0; i--) {
            if (sent.get(i).to().equalsIgnoreCase(email)) {
                return sent.get(i);
            }
        }
        throw new IllegalStateException("No email captured for " + email);
    }

    /** Extracts the plaintext 6-digit code from the last message sent to this email. */
    public String lastCodeFor(String email) {
        String body = lastFor(email).body();
        Matcher matcher = CODE_PATTERN.matcher(body);
        if (!matcher.find()) {
            throw new IllegalStateException("No 6-digit code found in captured email body: " + body);
        }
        return matcher.group(1);
    }

    public void clear() {
        sent.clear();
    }
}
